// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kAI_webAPI.Data;

#nullable disable

namespace kAI_webAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250622145258_AddRefreshTokenOnly")]
    partial class AddRefreshTokenOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kAI_webAPI.Models.Question.Question", b =>
                {
                    b.Property<int>("Id_question")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_question"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id_question");

                    b.HasIndex("Type");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Question.Questions_type", b =>
                {
                    b.Property<int>("Id_questype")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_questype"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment_vn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questype")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_questype");

                    b.ToTable("QuestionsTypes");
                });

            modelBuilder.Entity("kAI_webAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_users")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_users");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Subjects.Subjects", b =>
                {
                    b.Property<int>("Id_subjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_subjects"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<string>("subject_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.HasKey("Id_subjects");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("kAI_webAPI.Models.Subjects.SubjectsGroup", b =>
                {
                    b.Property<int>("Id_subgroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_subgroup"));

                    b.Property<int>("Subject1")
                        .HasColumnType("int");

                    b.Property<int>("Subject2")
                        .HasColumnType("int");

                    b.Property<int>("Subject3")
                        .HasColumnType("int");

                    b.Property<int?>("Subject4")
                        .HasColumnType("int");

                    b.Property<int?>("Subject5")
                        .HasColumnType("int");

                    b.HasKey("Id_subgroup");

                    b.HasIndex("Subject1");

                    b.HasIndex("Subject2");

                    b.HasIndex("Subject3");

                    b.HasIndex("Subject4");

                    b.HasIndex("Subject5");

                    b.ToTable("subjects_group", (string)null);
                });

            modelBuilder.Entity("kAI_webAPI.Models.Transcript.Remark", b =>
                {
                    b.Property<int>("Id_remark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_remark"));

                    b.Property<string>("Choose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_transcript")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_remark");

                    b.HasIndex("Id_transcript");

                    b.ToTable("Remark");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Transcript.Transcript", b =>
                {
                    b.Property<int>("Id_transcript")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_transcript"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id_transcript");

                    b.HasIndex("Id_user");

                    b.ToTable("Transcript");
                });

            modelBuilder.Entity("kAI_webAPI.Models.User.User", b =>
                {
                    b.Property<int>("Id_users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_users"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Question.Question", b =>
                {
                    b.HasOne("kAI_webAPI.Models.Question.Questions_type", "QuestionsType")
                        .WithMany("Questions")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionsType");
                });

            modelBuilder.Entity("kAI_webAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("kAI_webAPI.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("Id_users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Subjects.SubjectsGroup", b =>
                {
                    b.HasOne("kAI_webAPI.Models.Subjects.Subjects", "Subject1Navigation")
                        .WithMany()
                        .HasForeignKey("Subject1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kAI_webAPI.Models.Subjects.Subjects", "Subject2Navigation")
                        .WithMany()
                        .HasForeignKey("Subject2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kAI_webAPI.Models.Subjects.Subjects", "Subject3Navigation")
                        .WithMany()
                        .HasForeignKey("Subject3")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kAI_webAPI.Models.Subjects.Subjects", "Subject4Navigation")
                        .WithMany()
                        .HasForeignKey("Subject4")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kAI_webAPI.Models.Subjects.Subjects", "Subject5Navigation")
                        .WithMany()
                        .HasForeignKey("Subject5")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Subject1Navigation");

                    b.Navigation("Subject2Navigation");

                    b.Navigation("Subject3Navigation");

                    b.Navigation("Subject4Navigation");

                    b.Navigation("Subject5Navigation");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Transcript.Remark", b =>
                {
                    b.HasOne("kAI_webAPI.Models.Transcript.Transcript", "Transcript")
                        .WithMany()
                        .HasForeignKey("Id_transcript")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Transcript.Transcript", b =>
                {
                    b.HasOne("kAI_webAPI.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kAI_webAPI.Models.Question.Questions_type", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
